{
  imports = [
    ./agents-md.nix
    ./jarvismodes.nix
    ./alacritty.nix
    ./bat.nix
    ./chromium.nix
    ./eza.nix
    ./foot.nix
    ./git.nix
    ./hyprland
    ./lazygit.nix
    ./mpvpaper.nix
    ./neovim.nix
    ./obsidian.nix
    ./ranger.nix
    ./rofi.nix
    ./audiobook.nix
    ./starship.nix
    ./stylix.nix
    ./swaync
    ./tmux.nix
    ./waybar.nix
    ./wofi
    ./zathura.nix
    ./zsh.nix
  ];
}
